import 'dotenv/config';

const { PORT, MYSQL_HOST, MYSQL_USER, MYSQL_PASS, MYSQL_DB, ADMIN_EMAIL, ADMIN_USERNAME, ADMIN_PASSWORD, ADMIN_ROLE } = process.env;

export { PORT, MYSQL_HOST, MYSQL_USER, MYSQL_PASS, MYSQL_DB, ADMIN_EMAIL, ADMIN_USERNAME, ADMIN_PASSWORD, ADMIN_ROLE };
